### ISSUE TITLE
Hi amigos, can you help an Ember newby with a problem with ember-esri-loader ?

### ISSUE THREAD

**Issue by trokelado** [Esri/ember-esri-loader#24]
Problem: I´m getting espected layers but no stratified (one on top of next one).
probably cause dont know how to handle the template in Ember.

Details:
Using    ember-cli: 2.11.1   node: 6.10.3   os: win32 x64

Using the lazy load in maps.js route

import Ember from 'ember';

export default Ember.Route.extend({
  esriLoader: Ember.inject.service('esri-loader'),
  init () {
    this._super(...arguments);
        const esriLoader = this.get('esriLoader');
          esriLoader.load().catch(err => {       
             alert('entre al error de lazy load the JSAPI en init maps.js !');
          });
    }
});

Using a component named  esri-map.js as follows

import Ember from 'ember';
import layout from '../templates/components/esri-map';

export default Ember.Component.extend({
    layout,
    esriLoader: Ember.inject.service('esri-loader'),

   didInsertElement () {
      this._super(...arguments);
    
      this.get('esriLoader').loadModules(['esri/Map', 'esri/views/MapView', 'esri/Graphic', 'esri/geometry/Point', 'esri/geometry/Polyline', 'esri/geometry/Polygon', 'esri/symbols/SimpleLineSymbol', 'esri/symbols/SimpleMarkerSymbol', 'esri/symbols/SimpleFillSymbol']).then(modules => {
      const [Map, MapView, Graphic, Point, Polyline, Polygon, SimpleLineSymbol, SimpleMarkerSymbol, SimpleFillSymbol] = modules;      
     
      var map = new Map({
        basemap: 'satellite'  
      });            
        var view = new MapView({
        center: [-80, 35],
        //container: 'app-container', //when using this container renders nothing
        container: 'viewDiv',   //when using this container renders spected layers but not in stratified mode
        map: map,
        zoom: 3,
     });    
      
      // Create a point graphic //
      var point = new Point({
        longitude: -49.97,
        latitude: 41.73
      });

      // Create a symbol for drawing the point
      var markerSymbol = new SimpleMarkerSymbol({
        color: [226, 119, 40],
        outline: { // autocasts as new SimpleLineSymbol()
          color: [255, 255, 255],
          width: 2
        }
      });

      // Create a graphic and add the geometry and symbol to it
      var pointGraphic = new Graphic({
        geometry: point,
        symbol: markerSymbol
      });
       // Create a polyline graphic       
        // Create a line geometry with the coordinates of the line
      var polyline = new Polyline({
        paths: [
            [-111.30, 52.68],
            [-98, 49.5],
            [-93.94, 29.89]
          ]
      });    
      // Create a simple line symbol for rendering the line in the view
      var lineSymbol = new SimpleLineSymbol({
        color: [226, 119, 40],  // RGB color values as an array
        width: 4
      });
    
      // Create a simple object containing useful information relating to the feature
      var lineAtt = {
        Name: 'Keystone Pipeline',  // The name of the pipeline
        Owner: 'TransCanada',  // The owner of the pipeline
        Length: '3,456 km'  // The length of the pipeline
      };
    
      // Create the graphic
      var polylineGraphic = new Graphic({
        geometry: polyline,   
        symbol: lineSymbol,   
        attributes: lineAtt,   
        popupTemplate: {
          title: "{Name}",
          content: [{
            type: "fields",
            fieldInfos: [{
              fieldName: "Name"
            }, {
              fieldName: "Owner"
            }, {
              fieldName: "Length"
            }]
          }]
      }
    });

    //Create a polygon graphic
      // Create a polygon geometry
      var polygon = new Polygon({
        rings: [
          [-64.78, 32.3],
          [-66.07, 18.45],
          [-80.21, 25.78],
          [-64.78, 32.3]
        ]
      });

      // Create a symbol for rendering the graphic
      var fillSymbol = new SimpleFillSymbol({
        color: [227, 139, 79, 0.8],
        outline: { // autocasts as new SimpleLineSymbol()
          color: [255, 255, 255],
          width: 1
        }
      });

      // Add the geometry and symbol to a new graphic
      var polygonGraphic = new Graphic({
        geometry: polygon,
        symbol: fillSymbol
      });
  
      // Add the graphics to the view's graphics layer
      view.graphics.addMany([pointGraphic, polylineGraphic, polygonGraphic]);            
   })
  }  
});

my style file App.css contains

@import url('https://js.arcgis.com/3.21/esri/css/esri.css');

body, #viewDiv {
    padding: 0;
    margin: 0;
    height: 140%;
    width: 100%;
}

Using a template esri-map.hbs

<body>
  <div id="viewDiv"></div>

  <div class="app-container"> 
    {{view}} 
  </div>
</body>

Did I miss something ?
Hope you can see a solution
Thanks in advance
Enrique Gonzalez

**Comment by trokelado** [comment]
Sorry the template using is  esri-map.hbs
<body>
  <div id="viewDiv"></div>

  <div class="app-container"> 
    {{view}} 
  </div>
</body>

Enrique Gonzalez

**Comment by trokelado** [comment]
Sorrry connot insert the template here:

is just a HTML tag body two div  one with id= "viewDiv" and another div with class="App-container" with the {{view}} included
Enrique gonzalez

**Comment by tomwayson** [comment]
I can see what you pasted in the above comment:
```
<body>
  <div id="viewDiv"></div>

  <div class="app-container"> 
    {{view}} 
  </div>
</body>
```

Is that the template for your component, or the whole app? If it's the component's template, it should not include a `<body>` tag.

Also , the `{{view}}` is not needed, you can remove that.

Beyond those two changes, the template code looks OK.

All in all, your component JS code looks good to me. I'm not totally sure what you mean by:

> I´m getting espected layers but no stratified (one on top of next one).

This line: `view.graphics.addMany([pointGraphic, polylineGraphic, polygonGraphic]);` adds 3 graphics to the view's [graphics collection](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-View.html#graphics) which is a _single_ graphics layer. If you want each graphic in it's own layer (one on top of the next) you would have to [create multiple graphics layers and add them to the map](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GraphicsLayer.html) like:

```js
  var pointLayer = new GraphicsLayer({
    graphics: [pointGraphic]
  });
  map.addLayer(pointLayer);

  var polylineLayer = new GraphicsLayer({
    graphics: [polylineGraphic]
  });
  map.addLayer(polylineLayer);

  var polygonLayer = new GraphicsLayer({
    graphics: [polygonGraphic]
  });
  map.addLayer(polygonLayer);
```

Also, regarding this comment:
```js 
//container: 'app-container', //when using this container renders nothing
```

This is b/c the `container` needs to be an id, not a class name, and if you changed the template to be `<div id="app-container">` you would also need to add styles for that div, at least a height.

FYI to paste HTML into a github comment, use 3 backticks (```) - see the "Code" tab of https://guides.github.com/features/mastering-markdown/ for more info

**Comment by trokelado** [comment]
Hi Tom,


this is not stratified


________________________________
De: Tom Wayson <notifications@github.com>
Enviado: lunes, 24 de julio de 2017 03:08 p. m.
Para: Esri/ember-esri-loader
CC: trokelado; Author
Asunto: Re: [Esri/ember-esri-loader] Hi amigos, can you help an Ember newby with a problem with ember-esri-loader ? (#24)


I can see what you pasted in the above comment:

<body>
  <div id="viewDiv"></div>

  <div class="app-container">
    {{view}}
  </div>
</body>


Is that the template for your component, or the whole app? If it's the component's template, it should not include a <body> tag.

Also , the {{view}} is not needed, you can remove that.

Beyond those two changes, the template code looks OK.

All in all, your component JS code looks good to me. I'm not totally sure what you mean by:

I´m getting espected layers but no stratified (one on top of next one).

This line: view.graphics.addMany([pointGraphic, polylineGraphic, polygonGraphic]); adds 3 graphics to the view's graphics collection<https://developers.arcgis.com/javascript/latest/api-reference/esri-views-View.html#graphics> which is a single graphics layer. If you want each graphic in it's own layer (one on top of the next) you would have to create multiple graphics layers and add them to the map<https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GraphicsLayer.html> like:

  var pointLayer = new GraphicsLayer({
    graphics: [pointGraphic]
  });
  map.addLayer(pointLayer);

  var polylineLayer = new GraphicsLayer({
    graphics: [polylineGraphic]
  });
  map.addLayer(polylineLayer);

  var polygonLayer = new GraphicsLayer({
    graphics: [polygonGraphic]
  });
  map.addLayer(polygonLayer);

Also, regarding this comment:

//container: 'app-container', //when using this container renders nothing

This is b/c the container needs to be an id, not a class name, and if you changed the template to be <div id="app-container"> you would also need to add styles for that div, at least a height.

FYI to paste HTML into a github comment, use 3 backticks (```) - see the "Code" tab of https://guides.github.com/features/mastering-markdown/ for more info

**Comment by trokelado** [comment]
Hi Tom, Folowing your recomendations my problem still continues:

map.addLayer(pointLayer); // using this get TypeError: map.addLayer is not a function
map.addLayer(polylineLayer); //using this get TypeError: map.addLayer is not a function
map.addLayer(polygonLayer); //using this get TypeError: map.addLayer is not a function 
or
view.addLayer(pointLayer); // using this get TypeError: view.addLayer is not a function
view.addLayer(polylineLayer); //using this get TypeError: view.addLayer is not a function
view.addLayer(polygonLayer); //using this TypeError: view.addLayer is not a function
but
view.graphics.add(pointGraphic); // using this renders with not stratified layers. first the map then the graphic one after the other not on top 
view.graphics.add(polylineGraphic); // using this renders with not stratified layers. first the map then the graphic one after the other not on top 
view.graphics.add(polygonGraphic); // using this renders with not stratified layers. first the map then the graphic one after the other not on top

now the template of my component is just the div with id="viewDiv"

**Comment by tomwayson** [comment]
OK, well, at this point, I don't think your problem is not w/ the ember-esri-loader, but more of an issue of figuring out how to do what you want w/ the ArcGIS API for JavaScript. I suggest you get it working in JSBin first, then you can copy the code back into your ember app.

**Comment by trokelado** [comment]
Found the solution Tom,


just need the same versión on css


@import url('https://js.arcgis.com/4.4/esri/css/main.css')


Thanks for your tips


Enrique Gonzalez


________________________________
De: Tom Wayson <notifications@github.com>
Enviado: martes, 25 de julio de 2017 01:06 p. m.
Para: Esri/ember-esri-loader
CC: trokelado; Author
Asunto: Re: [Esri/ember-esri-loader] Hi amigos, can you help an Ember newby with a problem with ember-esri-loader ? (#24)


OK, well, at this point, I don't think your problem is not w/ the ember-esri-loader, but more of an issue of figuring out how to do what you want w/ the ArcGIS API for JavaScript. I suggest you get it working in JSBin first, then you can copy the code back into your ember app.

**Comment by tomwayson** [comment]
great, glad you got it working. closing this issue for now, feel free to re-open if needed.
