### ISSUE TITLE
Old Ember and Esri-loader versions

### ISSUE THREAD

**Issue by kasunvp** [Esri/ember-esri-loader#59]
The latest release of ember-esri-loader uses an old version of Ember. And also an old version of Esri-loader library.

Can you guys please update this? 

Thanks!

**Comment by tomwayson** [comment]
I agree that this is due for a bump in the esri-loader dependency. That should be just a matter of updating the version in package.json. If you want to give that a try in a PR I'll gladly review, merge and release.

I think it would also be nice to update Ember, but not critical unless that causing any issues in your app.

**Comment by NindroidX** [comment]
It might be interesting to update the ember app to the the new LTS release?

I can try to do this when I find some time.

**Comment by tomwayson** [comment]
Awesome @NindroidX!

I've used [ember update](componentWillReceiveProps) in the past for this, but I have not yet used that to go from v2.x to v3.x yet.

**Comment by tomwayson** [comment]
@kasunvp the bump to the latest esri-loader has been released as [v2.4.0](https://github.com/Esri/ember-esri-loader/releases/tag/v2.4.0)

**Comment by NindroidX** [comment]
@tomwayson I only used it to update between 3.X versions, so no 2 - 3 migration. I quickly tried it but ran into some weird errors, so I have to find some migration guides and spend more time with it.

**Comment by kasunvp** [comment]
Nice guys, thanks! :+1: 

I locally did the esri-loader upgrade and also tried upgrading the ember to latest LTS here. Also ran into issues as the migration is different than before. So have to spend more time with it. Let's see.

**Comment by Windvis** [comment]
Since https://github.com/Esri/ember-esri-loader/pull/63 was merged, I think this can be closed?
