### ISSUE TITLE
Ember-cli 3.5 breaks this addon

### ISSUE THREAD

**Issue by Windvis** [Esri/ember-esri-loader#61]
Our current project uses ember-cli 3.5 and when trying to use the esriLoader service an exception is thrown on this [loc](https://github.com/Esri/ember-esri-loader/blob/master/addon/services/esri-loader.js#L25).  After adding a breakpoint and looking at the source files, it looks like the esri-loader.js files aren't added to the /public/assets folder when that line executes, so esriLoader is still undefined at that point.

It might be related to [this issue](https://github.com/ember-cli/ember-cli/issues/8128) but I don't know enough about the ember build process and the way this addon works to be sure.

This problem only occurs on 3.5. I created a fresh 3.4 app and everything seems to work there.

**Comment by tomwayson** [comment]
Thanks for the feedback, I think I'll let https://github.com/ember-cli/ember-cli/issues/8128 shake out before we take any action here.

**Comment by tomwayson** [comment]
ah, good to know, I'll take a closer look then.

**Comment by kasunvp** [comment]
Oh, just noticed this. Nice finding @NindroidX :+1:

**Comment by kasunvp** [comment]
Looks like there's a temp fix for this https://github.com/ember-cli/ember-cli/issues/8128#issuecomment-431273388

**Comment by tomwayson** [comment]
The suggested fix in that issue breaks the dummy app (and presumably any pre-3.5 apps).

I'm reluctant to put special "if 3.5 then append 'public'" logic into this addon if that bug is going to be fixed.

**Comment by Windvis** [comment]
Everything seems to be working fine in Ember 3.6. Haven't checked Ember 3.5 again though.

**Comment by Windvis** [comment]
Just retested this in a dummy app (I can upload it somewhere if wanted). I updated from 3.4 to 3.5. Deleted the tmp and dist folders to be sure. Everything seems to work just fine. So I don't think this is a problem (or ever was..).

**Comment by tomwayson** [comment]
Thanks so much for the confirmation @Windvis!
