### ISSUE TITLE
Update esri-loader dependency version notation

### ISSUE THREAD

**Issue by Windvis** [Esri/ember-esri-loader#64]
At the moment the esri-loader dependency is defined like this: `"esri-loader": "~2.5.0"`.

How about changing that to `"esri-loader": "^2.5.0"`? That way we wouldn't have to manually keep these repos in sync.

**Comment by tomwayson** [comment]
resolved in #65

**Comment by Windvis** [comment]
@tomwayson This might not have been the smartest idea after all 😄.. I totally forgot that the ArcGIS css url also contains a version. So if you don't lock a specific ArcGIS version url in the esri-loader options, it is possible that your css version is not in sync with the ArcGIS Api version.

We noticed some problems with this in our app that is still in development. Some things related to the popups changed which needed styles that were not in the 4.9 release of the css file (I'm not sure if that is semver compliant 🤔).

Maybe a better solution would be to add esri-loader as a peer-dependency instead? And have the consuming project decide the (semver compatible) version?

**Comment by tomwayson** [comment]
ooops.

The peer dependency idea is interesting, but I don't really have the bandwidth to think that through, so for now I think for now I'd like to revert 626994cf98fbbe331aa9d59f7cc5d4aae5e6dc30 and cut a 2.5.1 release.

**Comment by Windvis** [comment]
I would manually update to esri-loader 2.6 though. That way ember-esri-loader 2.5.x = esri-loader 2.6 = ArcGIS 4.10.

**Comment by Windvis** [comment]
Also, the peerDependency variant works. I tried it by npm linking my local version of ember-esri-loader. The only thing that would be needed is update the docs to inform the users they need to manually add the version of esri-loader they want.

**Comment by Windvis** [comment]
Another option would be to integrate dependabot.
