### ISSUE TITLE
Use dependabot to keep esri-loader version in sync

### ISSUE THREAD

**Issue by Windvis** [Esri/ember-esri-loader#67]
With every release of esri-loader the version needs to manually be bumped in ember-esri-loader's package.json file.

It might be easier to setup [dependabot](https://dependabot.com/) (which is free for open source projects), to do that for you.

**Comment by tomwayson** [comment]
This is not a bad idea, but I could not get dependabot to install for esri repos

![image](https://user-images.githubusercontent.com/662944/51138334-ba356a80-17f5-11e9-80c2-d837f12ce091.png)

@jgravois have you set this up for an esri repo?

**Comment by jgravois** [comment]
> I could not get dependabot to install for esri repos

check out your screenshot, its trying to help you install dependabot on:

>  "your personal account @tomwayson"

i've never hooked up a dependency manager but [greenkeeper](https://greenkeeper.io/)  is an alternative option that:

* is already Esri approved
* is already used by @rgwozdz and co. in [koop-land](https://github.com/koopjs/koop-provider-agol/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aapp%2Fgreenkeeper).

![screenshot 2019-01-14 12 31 53](https://user-images.githubusercontent.com/3011734/51139353-7a23b700-17f8-11e9-92e0-9d364a867cd1.png)

FYI: in `react-arcgis` i recently had a user asking for pretty much the exact opposite of this and it ended up being the most convenient option to just lock the version of esri-loader.

https://github.com/Esri/react-arcgis/issues/75

**Comment by tomwayson** [comment]
The esri-loader updates themselves are not hard to manage (3-4x a year). The only reason I'm a little laid back about them is b/c our team is not yet using JSAPI 4.x, but that will be changing in the next couple of months, so I'll be more incentivized to keep esri-loader and this repo up to date w/ the JSAPI.

So the question is, would a bot make it more or less effort to keep up to date w/ ember's LTS releases?

I would not have considered using a bot to manage an ember repo before listening to https://embermap.com/podcast/incremental-ember-upgrades b/c I have always approached ember upgrades as a thing that must be done in a monolithic block. 

Even after listening to that, I'm still not 💯% convinced it's the right move for this repo, b/c we only care about LTS releases. We're already over the 2.18 - 3.4 hurdle, so I'm thinking I'll revisit this idea once the next LTS 3.8 is out. We'll see how much effort that is.

**Comment by tomwayson** [comment]
no longer needed after making esei-loader a peer dependency.
