### ISSUE TITLE
Unknown issue following 3.0.0 update

### ISSUE THREAD

**Issue by dreamfool** [Esri/ember-esri-loader#79]
We have a table gets populated with attributes from the points displayed on the map, showing at the lower part of the map.  The attributes have about 10 columns that is working fine with the original v2.9.0 but now it only load 2 columns and looks like it is on a loop and keep loading.  Data is in AGOL.  Got this error when debugging and wonder if this provides a clue?

```
index.js:163 Uncaught Error: Assertion Failed: You must call `this._super(...arguments);` when overriding `init` on a framework object. Please update <crashmap@service:crashmapdata::ember413> to call `this._super(...arguments);` from `init`.
    at assert (index.js:163)
    at Class._proto.<computed> [as __ASSERT_INIT_WAS_CALLED__ember1564610496677861481332005__] (object.js:131)
    at sendEvent (metal.js:465)
    at initialize (core_object.js:107)
    at Function.create (core_object.js:686)
    at FactoryManager.create (container.js:554)
    at instantiateFactory (container.js:358)
    at _lookup (container.js:290)
    at Container.lookup (container.js:134)
    at Class.lookup (container_proxy.js:78)
```

npm updated the following dependencies as well:

Package: @ember/jquery
  * Specified: ^0.6.1

Package: ember-cli
  * Specified: ^3.11.0

Package: ember-cli-dependency-checker
  * Specified: ^3.2.0

Package: ember-cli-htmlbars
  * Specified: ^3.1.0

Package: ember-cli-htmlbars-inline-precompile
  * Specified: ^1.0.5

Package: ember-cli-inject-live-reload
  * Specified: ^1.10.2

Package: ember-cli-template-lint
  * Specified: ^1.0.0-beta.3

Package: ember-data
  * Specified: ^3.11.4

Package: ember-esri-loader
  * Specified: ^3.0.0

Package: ember-lodash
  * Specified: ^4.19.5

Package: ember-paper
  * Specified: ^1.0.0-beta.26

Package: ember-power-select
  * Specified: ^2.3.5

Package: ember-responsive
  * Specified: ^3.0.5

Package: ember-source
  * Specified: ^3.11.1

Package: eslint-plugin-ember
  * Specified: ^5.4.0

Package: qunit-dom
  * Specified: ^0.8.5

Package: sass
  * Specified: ^1.22.7

Package: esri-loader
  * Specified: ^2.10.0

**Comment by tomwayson** [comment]
Hm..

Seems like the code in this addon always calls `this._super(...arguments);`:

https://github.com/Esri/ember-esri-loader/search?l=JavaScript&q=init

> npm updated the following dependencies as well

Is there any way you can reset to the last known good commit and only update ember-esri-loader and esri-loader and see if you still have this issue?

**Comment by dreamfool** [comment]
Thank you, my problem was resolved.
